# Generated by Django 4.1.4 on 2022-12-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Search",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keyword", models.TextField(blank=True, default="", null=True)),
                ("result_pos", models.TextField(blank=True, default="", null=True)),
                ("result_neg", models.TextField(blank=True, default="", null=True)),
            ],
        ),
    ]
